// <auto-generated />
using System;
using Desafio.Pokemon.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desafio.Pokemon.Data.EF.Migrations
{
    [DbContext(typeof(DesafioPokemonDbContext))]
    [Migration("20240912121208_CriarTabelaMestrePokemon")]
    partial class CriarTabelaMestrePokemon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Desafio.Pokemon.Business.Domain.MestrePokemon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Idade")
                        .HasMaxLength(3)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("mestresPokemon");
                });

            modelBuilder.Entity("Desafio.Pokemon.Business.Domain.MestrePokemon", b =>
                {
                    b.OwnsOne("Desafio.Pokemon.Business.Domain.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("MestrePokemonId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("TEXT")
                                .HasColumnName("Cpf");

                            b1.HasKey("MestrePokemonId");

                            b1.ToTable("mestresPokemon");

                            b1.WithOwner()
                                .HasForeignKey("MestrePokemonId");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
